#!/usr/bin/env node
/* ============================================================================
 *  generate-rules.mjs — build-time generator for firestore.rules
 * ----------------------------------------------------------------------------
 *  Reads infra.allowedEmails from src/config/tripConfig.ts and writes a
 *  firestore.rules that locks all reads/writes to that allow-list. Run via
 *  `npm run generate-rules` (and automatically on `npm run predeploy`).
 *
 *  The allow-list is the load-bearing access control — keep it in sync with
 *  the config, never hand-edit firestore.rules.
 * ========================================================================== */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const rulesPath = join(root, 'firestore.rules');

// Source the allow-list from VITE_ALLOWED_EMAILS — kept in .env (out of the public
// repo) so real addresses never land in version control. Falls back to a real
// process env var so CI can inject it too.
let envValue = process.env.VITE_ALLOWED_EMAILS || '';
try {
  const envFile = readFileSync(envPath, 'utf8');
  const m = envFile.match(/^\s*VITE_ALLOWED_EMAILS\s*=\s*(.*?)\s*$/m);
  if (m) envValue = m[1].trim().replace(/^['"]|['"]$/g, '');
} catch {
  /* no .env file — rely on process.env */
}

// Validate every entry — a bad address is a hard failure rather than a partial
// allow-list that silently locks out a real user.
const entries = envValue.split(',').map((e) => e.trim()).filter(Boolean);
const EMAIL = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const invalid = entries.filter((e) => !EMAIL.test(e));
if (invalid.length) {
  console.error(`✗ generate-rules: invalid email(s) in VITE_ALLOWED_EMAILS — refusing to write rules: ${invalid.join(', ')}`);
  process.exit(1);
}
const emails = entries;
if (emails.length === 0) {
  console.error('✗ generate-rules: VITE_ALLOWED_EMAILS is empty (set it in .env) — refusing to write open rules');
  process.exit(1);
}

const list = emails.map((e) => `          '${e}'`).join(',\n');

const rules = `rules_version = '2';

// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-rules.mjs from
// src/config/tripConfig.ts (infra.allowedEmails). DO NOT EDIT BY HAND —
// edit the config and run \`npm run generate-rules\` (runs on predeploy).
// Locked to the trip's allow-listed emails; everyone else is denied.
// ─────────────────────────────────────────────────────────────
service cloud.firestore {
  match /databases/{database}/documents {

    function isAllowed() {
      return request.auth != null
        && request.auth.token.email in [
${list}
        ];
    }

    match /{document=**} {
      allow read, write: if isAllowed();
    }
  }
}
`;

writeFileSync(rulesPath, rules);
console.log(`✓ firestore.rules generated — ${emails.length} allowed email(s): ${emails.join(', ')}`);
